---
- name: copy calico ip-ip pool config
  template:
    src: pool-conf.j2
    dest: /tmp/pool-conf.yml

- name: add calico ip-ip pool if required
  sudo: yes
  shell: calicoctl apply -f /tmp/pool-conf.yml
  environment:
    ETCD_AUTHORITY: "{{ calico_etcdaddr }}"
  run_once: True
  when: provider != 'openstack'
  tags:
    - calico

- name: copy calico profile config
  template:
    src: pool-conf.j2
    dest: /tmp/profile-conf.yml

- name: create calico profile
  sudo: yes
  shell: calicoctl apply -f /tmp/profile-conf.yml
  environment:
    ETCD_AUTHORITY: "{{ calico_etcdaddr }}"
  run_once: True
  tags:
    - calico
